/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wlw5SjOQ0oE
 */
"use client"
import { AvatarImage, AvatarFallback, Avatar } from "../ui/avatar"
import { Input } from "../ui/input"
import { Button } from "../ui/button"

export function chatui() {
  return (
    <div className="flex flex-col h-[480px] border rounded-lg">
      <div className="flex items-center justify-between p-4 border-b dark:border-gray-800">
        <div className="flex items-center space-x-4">
          <Avatar className="w-10 h-10">
            <AvatarImage alt="Mae Howard" src="/placeholder-user.jpg" />
            <AvatarFallback>MD</AvatarFallback>
          </Avatar>
          <div className="font-semibold">Mae Howard</div>
        </div>
        <div className="flex items-center space-x-4">
          <Avatar className="w-10 h-10">
            <AvatarImage alt="You" src="/placeholder-user.jpg" />
            <AvatarFallback>Y</AvatarFallback>
          </Avatar>
          <div className="font-semibold">You</div>
        </div>
      </div>
      <div className="flex-1 p-4 grid gap-4">
        <div className="flex items-start space-x-4">
          <div className="flex items-center">
            <Avatar className="w-8 h-8">
              <AvatarImage alt="Mae Howard" src="/placeholder-user.jpg" />
              <AvatarFallback>MD</AvatarFallback>
            </Avatar>
            <div className="flex flex-col">
              <div className="text-sm text-gray-500 dark:text-gray-400">Mae Howard</div>
              <div className="rounded-lg p-4 bg-gray-100 dark:bg-gray-800">Hey! How's it going?</div>
            </div>
          </div>
        </div>
        <div className="flex items-start space-x-4">
          <div className="flex items-center">
            <Avatar className="w-8 h-8">
              <AvatarImage alt="You" src="/placeholder-user.jpg" />
              <AvatarFallback>Y</AvatarFallback>
            </Avatar>
            <div className="flex flex-col">
              <div className="text-sm text-gray-500 dark:text-gray-400">You</div>
              <div className="rounded-lg p-4 bg-gray-100 dark:bg-gray-800">
                I'm doing great, thanks for asking! Did you get the files I sent over?
              </div>
            </div>
          </div>
        </div>
        <div className="flex items-end space-x-4 justify-end">
          <div className="flex items-center">
            <Avatar className="w-8 h-8">
              <AvatarImage alt="Mae Howard" src="/placeholder-user.jpg" />
              <AvatarFallback>MD</AvatarFallback>
            </Avatar>
            <div className="flex flex-col">
              <div className="text-sm text-gray-500 dark:text-gray-400">Mae Howard</div>
              <div className="rounded-lg p-4 bg-gray-100 dark:bg-gray-800">
                Yes, I've received them. I'll take a look and get back to you.
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex items-center p-4 border-t">
        <Input className="flex-1" placeholder="Type a message..." />
        <Button size="sm">Send</Button>
      </div>
    </div>
  )
}
